import './bootstrap';
import alpine from 'alpinejs';
import { registerGameLiveViewer } from './gameLiveViewer.js';
import { registerFfaLiveViewer } from './ffaLiveViewer.js';
import { registerTournamentGroupsLive } from './tournamentGroupsLive.js';
import { registerTournamentPlayoffLive } from './tournamentPlayoffLive.js';
import { registerTournamentJoinRequestsLive } from './tournamentJoinRequestsLive.js';
import { registerIndexLoadMore } from './indexLoadMore.js';
import { registerRefereeLogin } from './referee/refereeLogin.js';
import { registerRefereeGames } from './referee/refereeGames.js';
import { registerRefereeScoring } from './referee/refereeScoring.js';
import { registerLeagueRosterBoard } from './leagueRosterBoard.js';
import { registerRelatedUserSearch } from './relatedUserSearch.js';
import { registerCheckoutWheels } from './checkoutWheel.js';
import { registerFriendsPanel } from './friendsPanel.js';
import { registerPlayerCareer } from './playerCareer.js';

registerGameLiveViewer(alpine);
registerFfaLiveViewer(alpine);
registerTournamentGroupsLive(alpine);
registerTournamentPlayoffLive(alpine);
registerTournamentJoinRequestsLive(alpine);
registerIndexLoadMore(alpine);
registerRefereeLogin(alpine);
registerRefereeGames(alpine);
registerRefereeScoring(alpine);
registerLeagueRosterBoard(alpine);
registerRelatedUserSearch(alpine);
registerCheckoutWheels();
registerFriendsPanel(alpine);
registerPlayerCareer(alpine);

window.Alpine = alpine;
alpine.start();
